### ISSUE TITLE
Mapping DOID to UMLS ids

### ISSUE THREAD

**Issue by kenbabu** [dhimmel/disgenet#1]
Hi Daniel,
First I'd like to thank you for sharing your analysis scripts online as they help a great deal in helping advance bioinformatics knowledge. I am processing DisGeNet data as part of my disease gene prioritization pipeline similar to what you did here https://github.com/dhimmel/disgenet/blob/master/disgenet.ipynb. I am interested in how you generated mappings between DOIDs and UMLS ids. In your script you pass a url to the already generated mapping file. Would you please show me where you obtained the mappings as I'd like to work with the latest available data. The mapping file that I am referring to is

https://raw.githubusercontent.com/dhimmel/disease-ontology/72614ade9f1cc5a5317b8f6836e1e464b31d5587/data/xrefs-prop-slim.tsv

Thanks

**Comment by dhimmel** [comment]
The GitHub (non-raw-URL) for that file is https://github.com/dhimmel/disease-ontology/blob/052ffcc960f5897a0575f5feff904ca84b7d2c1d/data/xrefs-prop-slim.tsv. The commit hash in the URL is used for versioning. In the URL above, I use the latest commit hash, since I'm guessing that's what you want.

Check out the [README](https://github.com/dhimmel/disease-ontology/blob/052ffcc960f5897a0575f5feff904ca84b7d2c1d/README.md#directories) for a bit more information on the file:

> `xrefs-prop-slim.tsv` — cross-references for slim terms where diseases inherit all cross-references of the diseases they subsume.

It's created by the [`slim.ipynb` notebook](https://github.com/dhimmel/disease-ontology/blob/052ffcc960f5897a0575f5feff904ca84b7d2c1d/slim.ipynb).

See also our [discussion on "Unifying disease vocabularies"](https://doi.org/10.15363/thinklab.d44):

> We plan to propagate annotations from more specific terms to our slim terms. To facilitate this process, we created a propagated DO slim xref mapping file.

Regarding:

> I am interested in how you generated mappings between DOIDs and UMLS ids. In your script you pass a url to the already generated mapping file. Would you please show me where you obtained the mappings as I'd like to work with the latest available data.

We extract these mappings from the Disease Ontology which includes `xref` elements to map its terms to other resources such as UMLS. Propagation refers to us also mapping UMLS terms for child DOID terms to the parent DOID term.

Does this help answer your question?
